import type { ScryerOperationId } from './operation-identifiers'

export const ALL_SCRYER_OPERATION_IDS: ScryerOperationId[] = [
  'scryer.model.read',
  'scryer.model.search',
  'scryer.model.query',
  'scryer.rules.read',
  'scryer.codebase.read',
  'scryer.model.validate',
  'scryer.model.health',
  'scryer.plan.pending',
  'scryer.node.update',
  'scryer.link.add',
  'scryer.link.update',
  'scryer.link.delete',
  'scryer.node.set-subtree',
  'scryer.node.delete',
  'scryer.node.move',
  'scryer.responsibility.move',
  'scryer.group.set',
  'scryer.group.update',
  'scryer.group.delete',
  'scryer.person.add',
  'scryer.system.add',
  'scryer.container.add',
  'scryer.component.add',
  'scryer.group.add',
  'scryer.symbol.add',
  'scryer.source.update',
  'scryer.plan.fold',
  'scryer.model.set',
  'scryer.container.fill',
  'scryer.node.descope',
  'scryer.drift.get',
  'scryer.drift.flag',
  'scryer.drift.reconcile'
]
