export type ScryerOperationId =
  | 'scryer.model.read'
  | 'scryer.model.search'
  | 'scryer.model.query'
  | 'scryer.rules.read'
  | 'scryer.codebase.read'
  | 'scryer.model.validate'
  | 'scryer.model.health'
  | 'scryer.plan.pending'
  | 'scryer.node.update'
  | 'scryer.link.add'
  | 'scryer.link.update'
  | 'scryer.link.delete'
  | 'scryer.node.set-subtree'
  | 'scryer.node.delete'
  | 'scryer.node.move'
  | 'scryer.responsibility.move'
  | 'scryer.group.set'
  | 'scryer.group.update'
  | 'scryer.group.delete'
  | 'scryer.person.add'
  | 'scryer.system.add'
  | 'scryer.container.add'
  | 'scryer.component.add'
  | 'scryer.group.add'
  | 'scryer.symbol.add'
  | 'scryer.source.update'
  | 'scryer.plan.fold'
  | 'scryer.model.set'
  | 'scryer.container.fill'
  | 'scryer.node.descope'
  | 'scryer.drift.get'
  | 'scryer.drift.flag'
  | 'scryer.drift.reconcile'

export type ScryerLayer = 'plan' | 'committed'
export type ScryerTransport = 'cli' | 'ipc' | 'ui' | 'agent' | 'system' | 'test'
export type ScryerCaller = 'human' | 'agent' | 'system' | 'test'
export type ScryerOperationRisk = 'normal' | 'destructive' | 'high'
export type ScryerOperationClass =
  | 'structural_replacement'
  | 'structural_move'
  | 'model_correction'
  | 'generation_primitive'
  | 'ordinary_edit'
export type ScryerOperationWriteScope = 'whole_model' | 'subtree' | 'node' | 'responsibility'
export type ScryerOperationLockPolicy = 'none' | 'exclusive' | 'commit_if_writing'

export type ScryerOperationCapability =
  | 'read'
  | 'validate'
  | 'plan_diff'
  | 'plan_author'
  | 'source_author'
  | 'plan_fold'
  | 'model_generate'
  | 'model_correct'
  | 'drift_detect'
  | 'drift_record'
  | 'drift_reconcile'

export type ScryerOperationErrorCode =
  | 'invalid_input'
  | 'invalid_context'
  | 'incompatible_model'
  | 'io_error'
  | 'lock_busy'
  | 'lease_required'
  | 'operation_not_found'
  | 'internal_error'
  | 'not_found'
  | 'illegal_link'
  | 'validation_failed'
  | 'agent_run_required'

export type ScryerOperationEntity =
  | 'project'
  | 'node'
  | 'link'
  | 'group'
  | 'responsibility'
  | 'property'
  | 'source_entry'
  | 'boundary'
  | 'rule_topic'
  | 'agent_run'

export type ScryerMaintenanceWriteTarget =
  | 'sync'
  | 'anchor_baseline'
  | 'committed_source_map_reanchor'
  | 'history'
  | 'baseline'

export type ScryerOperationWarningCode = 'maintenance_write_failed'

export type ScryerStateRead =
  | 'planned'
  | 'committed'
  | 'committed_if_available'
  | 'rules'
  | 'project_tree'
  | 'sync'
  | 'anchors'
  | 'build_edges'
  | 'history'

export type ScryerSemanticWrite = 'planned' | 'committed'
export type ScryerMaintenanceWriteMode = 'required' | 'best_effort'

export type ScryerMaintenanceWrite = {
  target: ScryerMaintenanceWriteTarget
  mode: ScryerMaintenanceWriteMode
}

export type ScryerSideEffect =
  | 'baseline_refresh'
  | 'history_append'
  | 'sync_state_write'
  | 'anchor_baseline_refresh'
  | 'seed_sync_if_absent'
  | 'write_anchor_baseline_if_absent'
  | 'silent_reanchor_committed_source_map'
  | 'build_edges_read'
  | 'completion_gate'

export type ScryerValidationPolicy =
  | 'structural_warnings'
  | 'coverage_warnings'
  | 'anchor_warnings'
  | 'write_guards'
  | 'link_legality'
  | 'hierarchy_integrity'
  | 'group_integrity'
  | 'source_mapping_integrity'
  | 'fold_postconditions'
  | 'generation_postconditions'

export type ScryerValidationFindingCode =
  | 'destructive_change'
  | 'duplicate_id'
  | 'missing_reference'
  | 'invalid_hierarchy'
  | 'invalid_external'
  | 'empty_responsibility'
  | 'description_too_long'
  | 'invalid_symbol_name'
  | 'empty_symbol'
  | 'illegal_link'
  | 'invalid_group'
  | 'unknown_source_map_target'
  | 'unknown_boundary_target'
  | 'disconnected_node'
  | 'coverage_gap'
  | 'coverage_overlap'
  | 'anchor_range_warning'
  | 'invalid_drift_marker_transition'
  | 'no_op'

export type ScryerIdKind = 'node' | 'responsibility' | 'group' | 'link'
